// Loading
export const IS_LOADING = 'IS_LOADING';
export const IS_LOADED = 'IS_LOADED';

// Authentication
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const RESEND_EMAIL_VERIFICATION_LINK_FAIL =
    'RESEND_EMAIL_VERIFICATION_LINK_FAIL';
export const RESEND_EMAIL_VERIFICATION_LINK_SUCCESS =
    'RESEND_EMAIL_VERIFICATION_LINK_SUCCESS';
export const RESET_PASSWORD_TOKEN_SUCCESS = 'RESET_PASSWORD_TOKEN_SUCCESS';
export const RESET_PASSWORD_TOKEN_FAIL = 'RESET_PASSWORD_TOKEN_FAIL';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS';
export const EMAIL_VERIFICATION_FAIL = 'EMAIL_VERIFICATION_FAIL';

// errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// data refresh
export const AUTH_DATA_REFRESH = 'AUTH_DATA_REFRESH';
export const USER_PROFILE_DATA_REFRESH = 'USER_PROFILE_DATA_REFRESH';

// User
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';

// Subscriptions
export const UPDATE_SUBSCRIBED_USER_SUCCESS = 'UPDATE_SUBSCRIBED_USER_SUCCESS';
export const UPDATE_SUBSCRIBED_USER_FAIL = 'UPDATE_SUBSCRIBED_USER_FAIL';
export const FETCH_SUBSCRIPTIONS_SUCCESS = 'FETCH_SUBSCRIPTIONS_SUCCESS';
export const FETCH_SUBSCRIPTIONS_FAIL = 'FETCH_SUBSCRIPTIONS_FAIL';
export const REMOVE_SUBSCRIPTION_SUCCESS = 'REMOVE_SUBSCRIPTION_SUCCESS';
export const REMOVE_SUBSCRIPTION_FAIL = 'REMOVE_SUBSCRIPTION_FAIL';

// spreadsheets
export const FETCH_SPREADSHEETS_FROM_API_SUCCESS =
    'FETCH_SPREADSHEETS_FROM_API_SUCCESS';
export const FETCH_SPREADSHEETS_FROM_API_FAIL =
    'FETCH_SPREADSHEETS_FROM_API_FAIL';
export const FETCH_SPREADSHEET_TABS_SUCCESS = 'FETCH_SPREADSHEET_TABS_SUCCESS';
export const FETCH_SPREADSHEET_TABS_FAIL = 'FETCH_SPREADSHEET_TABS_FAIL';
export const ADD_SPREADSHEET_SUCCESS = 'ADD_SPREADSHEET_SUCCESS';
export const ADD_SPREADSHEET_FAIL = 'ADD_SPREADSHEET_FAIL';
export const FETCH_SUBSCRIBED_SPREADSHEETS_FROM_API_SUCCESS =
    'FETCH_SUBSCRIBED_SPREADSHEETS_FROM_API_SUCCESS';
export const FETCH_SUBSCRIBED_SPREADSHEETS_FROM_API_FAIL =
    'FETCH_SUBSCRIBED_SPREADSHEETS_FROM_API_FAIL';
export const REMOVE_SPREADSHEET_SUCCESS = 'REMOVE_SPREADSHEET_SUCCESS';
export const REMOVE_SPREADSHEET_FAIL = 'REMOVE_SPREADSHEET_FAIL';
export const CLEAR_SPREADSHEET_DATA = 'CLEAR_SPREADSHEET_DATA';
